on: push
name: Build and Deploy
jobs:
  installDependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      uses: Tgjmjgj/npm@specify-workspace-directory
      env:
        DIR: ./functions
      with:
        args: install
    - name: Collect coverage
      uses: Tgjmjgj/npm@specify-workspace-directory
      env:
        DIR: ./functions
      with:
        args: run coverage
    - name: Build project
      uses: Tgjmjgj/npm@specify-workspace-directory
      env:
        DIR: ./functions
      with:
        args: run build
    - name: Send coverage to codecov
      uses: Atrox/codecov-action@v0.1.2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Run tests
      uses: Tgjmjgj/npm@specify-workspace-directory
      env:
        DIR: ./functions
      with:
        args: t
    - name: Filter master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Deploy on Firebase
      uses: w9jds/firebase-action@7d6b2b058813e1224cdd4db255b2f163ae4084d3
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy --only functions
